[2025-05-30T00:15:59.557+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T00:15:59.760+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dependency_dag.task1 scheduled__2025-05-28T00:00:00+00:00 [queued]>
[2025-05-30T00:15:59.933+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dependency_dag.task1 scheduled__2025-05-28T00:00:00+00:00 [queued]>
[2025-05-30T00:15:59.942+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-30T00:16:00.248+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): task1> on 2025-05-28 00:00:00+00:00
[2025-05-30T00:16:00.369+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=163) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-30T00:16:00.378+0000] {standard_task_runner.py:72} INFO - Started process 175 to run task
[2025-05-30T00:16:00.358+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dependency_dag', 'task1', 'scheduled__2025-05-28T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/Sesion2/Ejemplo4.py', '--cfg-path', '/tmp/tmpx4cacg15']
[2025-05-30T00:16:00.389+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask task1
[2025-05-30T00:16:00.591+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T00:16:00.845+0000] {task_command.py:467} INFO - Running <TaskInstance: dependency_dag.task1 scheduled__2025-05-28T00:00:00+00:00 [running]> on host 31d54648d280
[2025-05-30T00:16:00.851+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T00:16:01.797+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dependency_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-28T00:00:00+00:00'
[2025-05-30T00:16:01.803+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T00:16:02.077+0000] {logging_mixin.py:190} INFO - Task 1
[2025-05-30T00:16:02.084+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-30T00:16:02.148+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T00:16:02.153+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dependency_dag, task_id=task1, run_id=scheduled__2025-05-28T00:00:00+00:00, execution_date=20250528T000000, start_date=20250530T001559, end_date=20250530T001602
[2025-05-30T00:16:02.352+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-30T00:16:02.541+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T00:16:02.565+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
