[2025-05-30T01:23:22.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T01:23:22.543+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flag_check_mysql_dag.execute_task scheduled__2025-05-29T01:00:00+00:00 [queued]>
[2025-05-30T01:23:22.624+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flag_check_mysql_dag.execute_task scheduled__2025-05-29T01:00:00+00:00 [queued]>
[2025-05-30T01:23:22.627+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-30T01:23:23.146+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): execute_task> on 2025-05-29 01:00:00+00:00
[2025-05-30T01:23:23.219+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'flag_check_mysql_dag', 'execute_task', 'scheduled__2025-05-29T01:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/Sesion3/Ejemplo7.py', '--cfg-path', '/tmp/tmpy3y05v7v']
[2025-05-30T01:23:23.255+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask execute_task
[2025-05-30T01:23:23.215+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1075) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-30T01:23:23.257+0000] {standard_task_runner.py:72} INFO - Started process 1091 to run task
[2025-05-30T01:23:23.334+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:23:23.567+0000] {task_command.py:467} INFO - Running <TaskInstance: flag_check_mysql_dag.execute_task scheduled__2025-05-29T01:00:00+00:00 [running]> on host 31d54648d280
[2025-05-30T01:23:23.583+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:23:24.519+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flag_check_mysql_dag' AIRFLOW_CTX_TASK_ID='execute_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-29T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-29T01:00:00+00:00'
[2025-05-30T01:23:24.522+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T01:23:24.695+0000] {logging_mixin.py:190} INFO - Flag detectado, ejecutando tarea...
[2025-05-30T01:23:24.704+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-30T01:23:24.725+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T01:23:24.727+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=flag_check_mysql_dag, task_id=execute_task, run_id=scheduled__2025-05-29T01:00:00+00:00, execution_date=20250529T010000, start_date=20250530T012322, end_date=20250530T012324
[2025-05-30T01:23:24.898+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-30T01:23:25.090+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T01:23:25.098+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
