[2025-06-04T01:29:52.316+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-04T01:29:52.337+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_dag_ej2_1.esperar_consumer_dag_S5_ej2_1 manual__2025-06-04T01:29:50.763828+00:00 [queued]>
[2025-06-04T01:29:52.346+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_dag_ej2_1.esperar_consumer_dag_S5_ej2_1 manual__2025-06-04T01:29:50.763828+00:00 [queued]>
[2025-06-04T01:29:52.347+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-04T01:29:52.361+0000] {taskinstance.py:2888} INFO - Executing <Task(ExternalTaskSensor): esperar_consumer_dag_S5_ej2_1> on 2025-06-04 01:29:50.763828+00:00
[2025-06-04T01:29:52.374+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10392) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-04T01:29:52.375+0000] {standard_task_runner.py:72} INFO - Started process 10395 to run task
[2025-06-04T01:29:52.378+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'final_dag_ej2_1', 'esperar_consumer_dag_S5_ej2_1', 'manual__2025-06-04T01:29:50.763828+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/Sesion5/Dataset_S5_4_1.py', '--cfg-path', '/tmp/tmp1xmuuuep']
[2025-06-04T01:29:52.381+0000] {standard_task_runner.py:105} INFO - Job 285: Subtask esperar_consumer_dag_S5_ej2_1
[2025-06-04T01:29:52.397+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-04T01:29:52.436+0000] {task_command.py:467} INFO - Running <TaskInstance: final_dag_ej2_1.esperar_consumer_dag_S5_ej2_1 manual__2025-06-04T01:29:50.763828+00:00 [running]> on host 31d54648d280
[2025-06-04T01:29:52.715+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='final_dag_ej2_1' AIRFLOW_CTX_TASK_ID='esperar_consumer_dag_S5_ej2_1' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T01:29:50.763828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T01:29:50.763828+00:00'
[2025-06-04T01:29:52.722+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-04T01:29:52.785+0000] {baseoperator.py:405} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-06-04T01:29:52.786+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:29:52.788+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97 DeprecationWarning: This method is deprecated and will be removed in future.
[2025-06-04T01:30:22.801+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:30:52.808+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:31:22.820+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:31:52.828+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:32:22.835+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:32:52.842+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:33:22.850+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:33:52.857+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:34:22.867+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:34:52.886+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:35:22.894+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:35:52.901+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:36:22.909+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:36:52.917+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:37:22.923+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:37:52.930+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:38:22.937+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:38:52.948+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:39:22.955+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:39:52.963+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:29:50.763828+00:00 ... 
[2025-06-04T01:39:52.981+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.1948371070002 seconds exceeds the specified timeout of 600.0.
[2025-06-04T01:39:52.995+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=final_dag_ej2_1, task_id=esperar_consumer_dag_S5_ej2_1, run_id=manual__2025-06-04T01:29:50.763828+00:00, execution_date=20250604T012950, start_date=20250604T012952, end_date=20250604T013952
[2025-06-04T01:39:53.014+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-04T01:39:53.016+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 285 for task esperar_consumer_dag_S5_ej2_1 (Sensor has timed out; run duration of 600.1948371070002 seconds exceeds the specified timeout of 600.0.; 10395)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.1948371070002 seconds exceeds the specified timeout of 600.0.
[2025-06-04T01:39:53.066+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-04T01:39:53.090+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-04T01:39:53.091+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
