[2025-05-30T01:23:43.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T01:23:43.754+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flag_check_mysql_dag.execute_task scheduled__2025-05-29T01:46:00+00:00 [queued]>
[2025-05-30T01:23:43.785+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flag_check_mysql_dag.execute_task scheduled__2025-05-29T01:46:00+00:00 [queued]>
[2025-05-30T01:23:43.787+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-30T01:23:43.807+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): execute_task> on 2025-05-29 01:46:00+00:00
[2025-05-30T01:23:43.828+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'flag_check_mysql_dag', 'execute_task', 'scheduled__2025-05-29T01:46:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/Sesion3/Ejemplo7.py', '--cfg-path', '/tmp/tmpdspetv88']
[2025-05-30T01:23:43.831+0000] {standard_task_runner.py:105} INFO - Job 157: Subtask execute_task
[2025-05-30T01:23:43.833+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1244) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-30T01:23:43.838+0000] {standard_task_runner.py:72} INFO - Started process 1250 to run task
[2025-05-30T01:23:43.848+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:23:43.907+0000] {task_command.py:467} INFO - Running <TaskInstance: flag_check_mysql_dag.execute_task scheduled__2025-05-29T01:46:00+00:00 [running]> on host 31d54648d280
[2025-05-30T01:23:43.911+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:23:44.054+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flag_check_mysql_dag' AIRFLOW_CTX_TASK_ID='execute_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-29T01:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-29T01:46:00+00:00'
[2025-05-30T01:23:44.057+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T01:23:44.088+0000] {logging_mixin.py:190} INFO - Flag detectado, ejecutando tarea...
[2025-05-30T01:23:44.089+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-30T01:23:44.100+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T01:23:44.101+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=flag_check_mysql_dag, task_id=execute_task, run_id=scheduled__2025-05-29T01:46:00+00:00, execution_date=20250529T014600, start_date=20250530T012343, end_date=20250530T012344
[2025-05-30T01:23:44.134+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-30T01:23:44.173+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T01:23:44.176+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
