[2025-05-30T01:24:06.642+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T01:24:06.736+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flag_check_mysql_dag.check_flag scheduled__2025-05-29T02:36:00+00:00 [queued]>
[2025-05-30T01:24:06.812+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flag_check_mysql_dag.check_flag scheduled__2025-05-29T02:36:00+00:00 [queued]>
[2025-05-30T01:24:06.832+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-30T01:24:07.146+0000] {taskinstance.py:2888} INFO - Executing <Task(SqlSensor): check_flag> on 2025-05-29 02:36:00+00:00
[2025-05-30T01:24:07.201+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-30T01:24:07.209+0000] {standard_task_runner.py:72} INFO - Started process 1415 to run task
[2025-05-30T01:24:07.200+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'flag_check_mysql_dag', 'check_flag', 'scheduled__2025-05-29T02:36:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/Sesion3/Ejemplo7.py', '--cfg-path', '/tmp/tmpcrz56f_3']
[2025-05-30T01:24:07.216+0000] {standard_task_runner.py:105} INFO - Job 200: Subtask check_flag
[2025-05-30T01:24:07.275+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:24:07.422+0000] {task_command.py:467} INFO - Running <TaskInstance: flag_check_mysql_dag.check_flag scheduled__2025-05-29T02:36:00+00:00 [running]> on host 31d54648d280
[2025-05-30T01:24:07.445+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T01:24:08.096+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flag_check_mysql_dag' AIRFLOW_CTX_TASK_ID='check_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-05-29T02:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-29T02:36:00+00:00'
[2025-05-30T01:24:08.098+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T01:24:08.281+0000] {base.py:84} INFO - Retrieving connection 'my_db_connection_mysql'
[2025-05-30T01:24:08.291+0000] {sql.py:96} INFO - Poking: SELECT flag FROM my_table WHERE id = 1 (with parameters None)
[2025-05-30T01:24:08.312+0000] {base.py:84} INFO - Retrieving connection 'my_db_connection_mysql'
[2025-05-30T01:24:08.337+0000] {sql.py:509} INFO - Running statement: SELECT flag FROM my_table WHERE id = 1, parameters: None
[2025-05-30T01:24:08.338+0000] {sql.py:518} INFO - Rows affected: 1
[2025-05-30T01:24:08.339+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-05-30T01:24:08.373+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T01:24:08.380+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=flag_check_mysql_dag, task_id=check_flag, run_id=scheduled__2025-05-29T02:36:00+00:00, execution_date=20250529T023600, start_date=20250530T012406, end_date=20250530T012408
[2025-05-30T01:24:08.536+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-30T01:24:08.792+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-30T01:24:08.798+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
